name : RebekahMonson.com
brand : Rebekah Monson
description : Rebekah Monson does technology, media, journalism and city stuff from beautiful Miami, Florida.
keyword : journalism, technology, miami, cities, millennials, engagement, human-centered design
url : https://rebekahmonson.github.io/
image: img/headshot.jpg
email : rebekah@whereby.us
twitter : rsm
facebook : rebekahmonson
medium : rsm
linkedin: rmonson
github : rebekahmonson
author : Rebekah Monson
year : 2016
markdown : kramdown
exclude :
  - node_modules
gems:
  - jemoji
