name : RebekahMonson.com
brand : Rebekah Monson
description : Technologist, Journalist, Designer, Urbanist, Dork
keyword : journalism, technology, miami, cities, millennials, engagement, human-centered design
url : http://rebekahmonson.github.io/
email : rebekah@whereby.us
twitter : rsm
github : rebekahmonson
author : Rebekah Monson
year : 2016
markdown : kramdown
exclude :
  - node_modules
